services:
  postgres:
    image: postgres:15-alpine
    container_name: insurance_postgres
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: malik
      POSTGRES_PASSWORD: malik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5999:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U insurance_user -d insurance_db"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

#  insurance-api:
#    build: .
#    container_name: insurance_api
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/insurance_db
#      SPRING_DATASOURCE_USERNAME: malik
#      SPRING_DATASOURCE_PASSWORD: malik
#      SPRING_JPA_HIBERNATE_DDL-AUTO: update
#    ports:
#      - "8080:8080"
#    restart: unless-stopped

volumes:
  postgres_data: